dist: trusty
sudo: required
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build and publish
  - deploy
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: 1.8.0.+
      install: skip
      script:
        - APPLICATION=pal-tracker
        - ./gradlew clean :applications:${APPLICATION}-server:build
      before_deploy:
        - git config --local user.name "anshul-lab"
        - git config --local user.email "anshulgupta2tcs@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy: &github
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "build/libs/${APPLICATION}.jar"
        skip_cleanup: true
